export const websiteCopyStrings = {
  navBarHome: 'Home',
  navBarProducts: 'Products',
  navBarDeveloper: 'Developer',
  navBarCompany: 'Company',
  navBarProductJinaCore: 'Jina Core',
  navBarProductJinaHub: 'Jina Hub',
  navBarProductJinaDashboard: 'Jina Dashboard',
  navBarDevelopersContribute: 'Contribute',
  navBarDevelopersLearn: 'Learn',
  navBarDevelopersJoin: 'Join',
  navBarCompanyAbout: 'About us',
  navBarCompanyCareers: 'Careers',
  navBarCompanyContact: 'Contact us',
  navBarCompanyBlog: 'Blog',
  buttonCallToAction: 'Try it out!',
  footerPhoneNumber: '+880 112 345 678',
  footerAddress: '711-2880 Nulla St. Mankato Mississippi 96522',
  footerCompany: 'Company',
  footerCompanyAbout: 'About us',
  footerCompanyCareers: 'Careers',
  footerCompanyContact: 'Contact us',
  footerCompanyBlog: 'Blog',
  footerProducts: 'Products',
  footerProductsHub: 'Hub',
  footerProductsCore: 'Core',
  footerProductsDashboard: 'Dashboard',
  footerDevelopers: 'Developers',
  footerDevelopersContribute: 'Contribute',
  footerDevelopersLearn: 'Learn',
  footerDevelopersJoin: 'Join',
  footerSocials: 'Socials',
  footerSocialsGitHub: 'GitHub',
  footerSocialsLinkedin: 'LinkedIn',
  footerSocialsTwitter: 'Twitter',
  footerSocialsSlack: 'Slack'
}
