export const websiteCopyStrings = {
  heroHeadline: 'Reimagine search with AI',
  heroDescription:
    'Jina is an easier way to build neural search on the cloud. Our open source ecosystem lets you build and deploy search pipelines for any kind of data within seconds!',
  heroPrimaryButton: 'Try it out',
  heroSecondaryButton: 'Latest release',
  HomeCallToActionTitle: 'Like What You See?',
  HomeCallToActionDescription:
    'Jina is an easier way to build neural search on the cloud. Our open source ecosystem lets you build and deploy search pipelines for any kind of data within seconds!',
  HomeCallToActionButtonLabel: 'Try it on',
  valuePropositionTimeSaverTitle: 'Timesaver',
  valuePropositionTimeSaverDescription:
    'Get started with neural search within minutes! No more stitching together systems for your search pipeline.',
  valuePropositionDataSupportTitle: 'Universal data support',
  valuePropositionDataSupportDescription:
    'Use and get support for all kinds of data types! Enjoy the numerous available state-of-the-art Machine Learning libraries.',
  valuePropositionCommunityDrivenTitle: 'Community driven',
  valuePropositionCommunityDrivenDescription:
    'Thrive in the Open Source community! Help Jina grow by contributing and benefit from wonderful work done by others!',
  valuePropositionPlugAndPlayTitle: 'Plug and play',
  valuePropositionPlugAndPlayDescription:
    'Easily extend and customize leveraging community-driven components. Build search pipelines within seconds.',
  navBarHome: 'Home',
  navBarProducts: 'Products',
  navBarDeveloper: 'Developer',
  navBarCompany: 'Company',
  navBarProductJinaCore: 'Jina Core',
  navBarProductJinaHub: 'Jina Hub',
  navBarProductJinaDashboard: 'Jina Dashboard',
  navBarDevelopersContribute: 'Contribute',
  navBarDevelopersLearn: 'Learn',
  navBarDevelopersJoin: 'Join',
  navBarCompanyAbout: 'About us',
  navBarCompanyCareers: 'Careers',
  navBarCompanyContact: 'Contact us',
  navBarCompanyBlog: 'Blog',
  navBarButtonCallToAction: 'Try it out!',
  footerPhoneNumber: '+880 112 345 678',
  footerAddress: '711-2880 Nulla St. Mankato Mississippi 96522',
  footerCompany: 'Company',
  footerCompanyAbout: 'About us',
  footerCompanyCareers: 'Careers',
  footerCompanyContact: 'Contact us',
  footerCompanyBlog: 'Blog',
  footerProducts: 'Products',
  footerProductsHub: 'Hub',
  footerProductsCore: 'Core',
  footerProductsDashboard: 'Dashboard',
  footerDevelopers: 'Developers',
  footerDevelopersContribute: 'Contribute',
  footerDevelopersLearn: 'Learn',
  footerDevelopersJoin: 'Join',
  footerSocials: 'Socials',
  footerSocialsGitHub: 'GitHub',
  footerSocialsLinkedin: 'LinkedIn',
  footerSocialsTwitter: 'Twitter',
  footerSocialsSlack: 'Slack',
  navBarCompanyEvents: 'Events',
  navBarCompanyNews: 'News',
  subscribeTitle: 'Never Miss an Update',
  subscribeSubtitle: 'Stay up to date with our latest news',
  subscribeButtonLabel: 'Subscribe',
  subscribeInputPlaceholder: 'Your email',
  subscribeInputErrorMessage: 'Email is not valid'
}
