export const websiteCopyStrings = {
  heroHeadline: 'Reimagine search with AI',
  heroDescription:
    'Jina is an easier way to build neural search on the cloud. Our open source ecosystem lets you build and deploy search pipelines for any kind of data within seconds!',
  heroPrimaryButton: 'Try it out',
  heroSecondaryButton: 'Latest release',
  HomeCallToActionTitle: 'Like What You See?',
  HomeCallToActionDescription:
    'Jina is an easier way to build neural search on the cloud. Our open source ecosystem lets you build and deploy search pipelines for any kind of data within seconds!',
  HomeCallToActionButtonLabel: 'Try it on',
  valuePropositionTimeSaverTitle: 'Timesaver',
  valuePropositionTimeSaverDescription:
    'Get started with neural search within minutes! No more stitching together systems for your search pipeline.',
  valuePropositionDataSupportTitle: 'Universal data support',
  valuePropositionDataSupportDescription:
    'Use and get support for all kinds of data types! Enjoy the numerous available state-of-the-art Machine Learning libraries.',
  valuePropositionCommunityDrivenTitle: 'Community driven',
  valuePropositionCommunityDrivenDescription:
    'Thrive in the Open Source community! Help Jina grow by contributing and benefit from wonderful work done by others!',
  valuePropositionPlugAndPlayTitle: 'Plug and play',
  valuePropositionPlugAndPlayDescription:
    'Easily extend and customize leveraging community-driven components. Build search pipelines within seconds.',
  careersWorkingWithUsSectionHeadingPart1: 'Working with',
  careersWorkingWithUsSectionHeadingPart2: 'Us',
  careersWorkingWithUsNationalitiesTitle: 'Nationalities',
  careersWorkingWithUsNationalitiesAmount: '11+',
  careersWorkingWithUsLanguagesTitle: 'Languages',
  careersWorkingWithUsLanguagesAmount: '12+',
  careersWorkingWithUsTechnologiesTitle: 'Technoloies',
  careersWorkingWithUsTechnologiesAmount: '20+',
  navBarHome: 'Home',
  navBarProducts: 'Products',
  navBarDeveloper: 'Developer',
  navBarCompany: 'Company',
  navBarProductJinaCore: 'Jina Core',
  navBarProductJinaHub: 'Jina Hub',
  navBarProductJinaDashboard: 'Jina Dashboard',
  navBarDevelopersContribute: 'Contribute',
  navBarDevelopersLearn: 'Learn',
  navBarDevelopersJoin: 'Join',
  navBarCompanyAbout: 'About us',
  navBarCompanyCareers: 'Careers',
  navBarCompanyContact: 'Contact us',
  navBarCompanyBlog: 'Blog',
  navBarButtonCallToAction: 'Try it out!',
  aboutWhyWeStartedJinaTitlePart1: 'Why we started',
  aboutWhyWeStartedJinaTitlePart2: 'Jina',
  aboutWhyWeStartedJinaDescriptionPart1:
    'Deep learning technology is transforming how we interact with and make use of all the data whether it is scientific applications, consumer software or internal enterprise systems.',

  aboutWhyWeStartedJinaDescriptionPart2:
    'Jina AI was started to provide a solution ready to keep up with the emerging needs for all kinds of search. As the need to process large quantities of data grows, Jina helps you to stay on top of the ever changing data landscape.',
  OfficesSecionTitlePart1: 'Our',
  OfficesSecionTitlePart2: 'Offices',
  Offices1TitlePart1: 'Berlin,',
  Offices1TitlePart2: 'Germany',
  Offices1Description: 'Some description',
  Offices2TitlePart1: 'Beijing,',
  Offices2TitlePart2: 'China',
  Offices2Description: 'Some description',
  Offices3TitlePart2: 'Global',
  Offices3Description: 'Some description',
  aboutInvestorsSectionTitlePart1: 'Our',
  aboutInvestorsSectionTitlePart2: 'Investors',
  footerPhoneNumber: '+880 112 345 678',
  footerAddress: '711-2880 Nulla St. Mankato Mississippi 96522',
  footerCompany: 'Company',
  footerCompanyAbout: 'About us',
  footerCompanyCareers: 'Careers',
  footerCompanyContact: 'Contact us',
  footerCompanyBlog: 'Blog',
  footerProducts: 'Products',
  footerProductsHub: 'Hub',
  footerProductsCore: 'Core',
  footerProductsDashboard: 'Dashboard',
  footerDevelopers: 'Developers',
  footerDevelopersContribute: 'Contribute',
  footerDevelopersLearn: 'Learn',
  footerDevelopersJoin: 'Join',
  footerSocials: 'Socials',
  footerSocialsGitHub: 'GitHub',
  footerSocialsLinkedin: 'LinkedIn',
  footerSocialsTwitter: 'Twitter',
  footerSocialsSlack: 'Slack',
  navBarCompanyEvents: 'Events',
  navBarCompanyNews: 'News',
  careersWhatWeStandForSectionTitlePart1: 'What We',
  careersWhatWeStandForSectionTitlePart2: 'Stand for',
  careersWhatWeStandForTitle1: 'We believe in open source',
  careersWhatWeStandForDescription1:
    'We are all open source evangelists and believe that open source is the right approach to make deep learning technology truly accessible.',
  careersWhatWeStandForTitle2: 'We are a global team',
  careersWhatWeStandForDescription2:
    'We have offices in Berlin and Beijing and some of our teammates work completely remote around the world.',
  careersWhatWeStandForTitle3: 'We stick to our values',
  careersWhatWeStandForDescription3:
    'We work on moral and ethical principles like honesty, integrity, dependability, and trustworthiness.',
  careersWhatWeStandForTitle4: 'We welcome fresh perspectives',
  careersWhatWeStandForDescription4:
    "We respect each other's unique cultures, beliefs, skills, and qualities. And we work towards creating a safe, fair, and inclusive working environment.",
  careersWhatWeStandForTitle5: 'We encourage ownership',
  careersWhatWeStandForDescription5:
    'We encourage everyone to take ownership of their work and show high autonomy. Take initiative, step up for your ideas, and commit to execution and performance.',
  careersWhatWeStandForTitle6: 'We work together as one',
  careersWhatWeStandForDescription6:
    'Collaboration is essential, whether that’s inside or between teams. It means less wasted effort and makes for better work. We aim to work closely and transparently and bring the right people in as early as possible.',
  contributeResourcesHeaderPart1: 'Resources',
  contributeResourcesHeaderPart2: 'for contributors',
  contributeResourcesGitHubTitle: 'GitHub',
  contributeResourcesGitHubCopy:
    'Our Flow architecture follows a modular design. Easily plug and play with existing solutions!',
  contributeResourcesGitHubLearnMoreLink: 'https://github.com/jina-ai/jina',
  contributeResourcesArticlesTitle: 'Articles',
  contributeResourcesArticlesCopy:
    'Our Flow architecture follows a modular design. Easily plug and play with existing solutions!',
  contributeResourcesArticlesLearnMoreLink: 'https://github.com/jina-ai/jina',
  contributeResourcesSlackTitle: 'Slack',
  contributeResourcesSlackCopy:
    'Our Flow architecture follows a modular design. Easily plug and play with existing solutions!',
  contributeResourcesSlackLearnMoreLink:
    'https://join.slack.com/t/jina-ai/shared_invite/zt-rgm1cxdu-v_uuLntO7VB18o8eH_ZHuA',
  contributeResourcesNewsletterTitle: 'NewsLetter',
  contributeResourcesNewsletterCopy:
    'Our Flow architecture follows a modular design. Easily plug and play with existing solutions!',
  contributeResourcesNewsletterLearnMoreLink: 'https://github.com/jina-ai/jina',
  contributeResourcesLearnMore: 'Learn more'
}
